### PR TITLE
Fix issue 815

### PR DESCRIPTION
**Pull request by mrnfrancesco**

### CODE REVIEW

**Comment by mrnfrancesco** [comment]
In my opinion, the `Time.parse('2000-01-01')` expedient is better located into `update_required?` because in `last_update` it would give a wrong information.

If I just downloaded wpscan and run `wpscan --version`, I think it's better to see nothing instead of a date which is obviously a fake.

**Comment by ethicalhack3r** [comment]
:+1:

**Comment by ethicalhack3r** [comment]
I'll just wait on a second opinion before merging. Thanks for the pull request! :)

**Comment by FireFart** [comment]
looks good to me

**Pull request merged**
