### PR TITLE
Update config_backups.txt

### PR DESCRIPTION
**Pull request by Ehsan-Nezami**
My experience shows this list on most sites.

## Licensing

By submitting code contributions to the WPScan development team via Github Pull Requests, or any other method, it is understood that the contributor is offering the WPScan company (company number 	83421476900012), which is registered in France, the unlimited, non-exclusive right to reuse, modify, and relicense the code.

### CODE REVIEW

**Comment by erwanlr** [comment]
This file is just for specs, the list used is there https://data.wpscan.org/config_backups.txt and contains the most common files we have identified.

**Comment by Ehsan-Nezami** [comment]
So please add these:
wp-config.php1
wp-config.php.1
wp-config.zip
wp-config.tar

**Comment by Ehsan-Nezami** [comment]
Thank you very much if you can add my name to a contributor :)

**Comment by ethicalhack3r** [comment]
To be added to Github's contributor list your PR needs to be accepted. This is done automatically by Github, and we can not edit it manually. We do not keep any other contributor lists.

**Pull request closed without merging**
