### PR TITLE
Initial commit of JSON logging hackery

### PR DESCRIPTION
**Pull request by sempervictus**
Update the wp_options configuration to take a --json-file param,
turning it into a runtime ivar for the main script.

Implement ivar_to_hash returning a hash of String k,v for each of
the objects instance variables and their values. Hack around
nested vulnerabilitites Arrays and Hash objects.

Maintain a running match_log hash during the main method, updating
it with object attributes other runtime outputs.

Write out final match_log hash to a JSON file at completion.

-----

This is obviously not ideal, i just hacked up the CLI to accumulate data from the object's resolution. The way the actual scanner object interfaces are set up doesn't provide for an easy method of acquiring that data via callbacks or shared state. It produces machine output, has been working fine for a while, recently noticed a ping on #198 in my email and remembered that i should PR this :).

Resulting data should be enough to map into VA's, throw directly in ElasticSearch, or feed into MSF/wpsploit.

### CODE REVIEW

**Comment by ethicalhack3r** [comment]
I will have a proper look into the changes when I have a bit more time, just wanted to let you know that I'd seen it, thanks!

**Comment by sempervictus** [comment]
@ethicalhack3r: thanks boss, once the Q4 insanity settles a bit i'll see if theres anything else i can export here or more likely from the slightly altered wpsploit version i have.

**Comment by theabraxas** [comment]
haha oh man i just spent time writing a crappy python converter from the CLI output to a json file. x.x

**Comment by erwanlr** [comment]
Closing as the v3 supports JSON output and to a file as well (```--format json --output /path/to/out.json```)

Thank you for submitting the PR though :)

**Pull request closed without merging**
