### PR TITLE
Remove license from readme

### PR DESCRIPTION
**Pull request by surfer190**
* Change licence to markdown

---

No one wants to read the licence first, so why is it at the top of the readme?

I have added a link at the bottom of the readme to the licence

### CODE REVIEW

**Comment by ethicalhack3r** [comment]
Personally I like it where it is. There's no excuse if we find someone using WPScan commercially without a commercial license that they did not see it.

**Comment by surfer190** [comment]
I think I get your point of view, you are looking from a business perspective. A user seeing the licence, is more important than quickly getting started and using wpscan.

**Comment by FireFart** [comment]
I also think the user can scroll the few lines over the license.

It's not only from a business perspective. We put the license in place to prevent automated scanner as a service platforms to use our data wihtout proper attribution or giving something back to the community. Sad story but it happened more than one time....

**Comment by surfer190** [comment]
That's a shame

**Pull request closed without merging**
