### PR TITLE
Virtualhost support

### PR DESCRIPTION
**Pull request by stefancastille**
Add support for virtual hosts
command line argument --virtualHost wordpress.mydomain.com will set the Host-header in requests to wordpress.mydomain.com

Allows you to test sites where the forward DNS lookup does not match the IP of the server you wish to test:
- old installation where the DNS has been changed to the new setup
- new test installation
- server behind a CDN where you want to bypass the CDN while testing
- ...

### CODE REVIEW

**Comment by FireFart** [comment]
Personally i would prefer `--host xxxx` as the option name. @wpscanteam/owners what do you think?

**Comment by ethicalhack3r** [comment]
:+1:

**Comment by pvdl** [comment]
```-- host xxxx``` sounds good to me.
BTW :+1:

**Comment by erwanlr** [comment]
--host or --vhost is fine for me :p

**Comment by stefancastille** [comment]
--vhost is fine for me. --host might be confusing.

How does this work, do I make the change or can I assume that the change to --vhost / --host will be made by the maintainers when/if they merge the code?

**Comment by FireFart** [comment]
you can edit the code on your branch and repush it to the remote branch and this pull request will be updated automagically :D

**Comment by stefancastille** [comment]
updated to --vhost

**Comment by erwanlr** [comment]
Tested & working :)

**Pull request merged**
