### PR TITLE
Apiv2

### PR DESCRIPTION
**Pull request by ethicalhack3r**

### CODE REVIEW

**Comment by FireFart** [comment]
I would change the text from ` |  Latest version: 2.3.8` to ` |  Latest version available: 2.3.8`

**Comment by FireFart** [comment]
Or even only print it if latest_version > current_version and say something like `update available`

**Comment by ethicalhack3r** [comment]
Version output look better @FireFart ?

**Comment by ethicalhack3r** [comment]
Going to use ```#lesser_or_equal?```

**Comment by ethicalhack3r** [comment]
Implemented new method called ```lesser?```

**Pull request merged**
